"
I am an controller of OKModuleRelationshipLink.
"
Class {
	#name : #OKModuleRelationshipLinkController,
	#superclass : #OPRelationshipController,
	#traits : 'OKTModuleRelationshipLinkController',
	#classTraits : 'OKTModuleRelationshipLinkController classTrait',
	#category : 'OpenPonk-Modularity-Controllers'
}

{ #category : #accessing }
OKModuleRelationshipLinkController >> target [
	^ target
	"remove this method if similar one gets implemented in my superclass"
]
