language: smalltalk
sudo: false

os:
  - linux

matrix:
  include:
    - smalltalk: Pharo64-7.0
    - smalltalk: Pharo32-8.0
    - smalltalk: Pharo64-8.0
    - smalltalk: Pharo64-9.0
  allow_failures:
    - smalltalk: Pharo64-9.0
