SystemOrganization addCategory: #'OpenPonk-Kendrick-modularity'!
SystemOrganization addCategory: 'OpenPonk-Kendrick-modularity-Bridge'!
SystemOrganization addCategory: 'OpenPonk-Kendrick-modularity-KendrickFSM'!
SystemOrganization addCategory: 'OpenPonk-Kendrick-modularity-KendrickFSMBridge'!
SystemOrganization addCategory: 'OpenPonk-Kendrick-modularity-Modularity'!
SystemOrganization addCategory: 'OpenPonk-Kendrick-modularity-Spec'!
